### ISSUE TITLE
User System Development Tracker 

### ISSUE THREAD

**Issue by hanisirfan** [hadiirfan/eKV#8]
All development progress of the user system is listed here.

- [x] Basic user login and logout
- [x] Basic user registration
- [x] Add validation when registering user
- [x] Improve login page UI //Maybe the design will be changed soon.
- [x] Improve user registration page (this is related to admin page as a whole)
- [x] User profile
- [x] User profile picture
